.PHONY: all CosinusHyperbolique croissance_rapide erreurSinus expo_minoree exponentielle Expo_Switch fibonacci sinabsint Sinus_Retardee VAbsolue_Sinus xCarre
all: CosinusHyperbolique croissance_rapide erreurSinus expo_minoree exponentielle Expo_Switch fibonacci sinabsint Sinus_Retardee VAbsolue_Sinus xCarre

CosinusHyperbolique:
	$(MAKE) -C $@

croissance_rapide:
	$(MAKE) -C $@

erreurSinus:
	$(MAKE) -C $@

expo_minoree:
	$(MAKE) -C $@

exponentielle:
	$(MAKE) -C $@

Expo_Switch:
	$(MAKE) -C $@

fibonacci:
	$(MAKE) -C $@

sinabsint:
	$(MAKE) -C $@

Sinus_Retardee:
	$(MAKE) -C $@

VAbsolue_Sinus:
	$(MAKE) -C $@

xCarre:
	$(MAKE) -C $@
